type ComponentStyles = Record<string, React.CSSProperties>;

export const MotoristaStyles: ComponentStyles = {
	mainContainer: {
		minHeight: '100%',
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'center',
		overflowY: 'auto',
	},
	wallpaperContainer: {
		flex: 1,
		width: '100%',
		maxWidth: '600px',
		display: 'flex',
		flexDirection: 'column',
		alignItems: 'center',
		padding: '20px',
		boxSizing: 'border-box',
		position: 'relative',
	},
	wallpaperOverlay: {
		position: 'absolute',
		width: '100vw',
		height: '100%',
		backgroundColor: 'rgba(0, 0, 0, 0.8)',
		zIndex: 1,
	},
	title: {
		textAlign: 'center',
		marginBottom: '30px',
		fontSize: '2.2rem',
		fontWeight: 'bold',
		textShadow: '0 1px 2px rgba(0,0,0,0.5)',
		zIndex: 3,
	},
	formContainer: {
		position: 'relative',
		zIndex: 2,
		width: '80%',
		maxWidth: '350px',
		display: 'flex',
		gap: '1rem',
		flexDirection: 'column',
		alignItems: 'center',
		padding: '20px',
		borderRadius: '15px',
		boxShadow: '0 6px 20px rgba(0, 0, 0, 0.4)',
	},
	submitButton: {
		display: 'flex',
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		width: 'calc(100% - 40px)',
		maxWidth: '400px',
		padding: '15px 20px',
		marginTop: '20px',
		borderRadius: '10px',
		fontSize: '1.2rem',
		fontWeight: 'bold',
		border: 'none',
		cursor: 'pointer',
		boxShadow: '0 4px 8px rgba(0, 0, 0, 0.2)',
		transition: '0.5s ease',
	},
	submitButtonBlue: {
		display: 'flex',
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		width: 'calc(100% - 40px)',
		maxWidth: '400px',
		padding: '15px 20px',
		marginTop: '10px',
		borderRadius: '10px',
		backgroundColor: '#5C6BC0',
		fontSize: '1.2rem',
		fontWeight: 'bold',
		border: 'none',
		cursor: 'pointer',
		boxShadow: '0 4px 8px rgba(0, 0, 0, 0.2)',
		transition: 'background-color 0.5s ease',
	},
	logoContainer: {
		textAlign: 'center',
		marginBottom: '30px',
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		flexDirection: 'column',
		gap: '1rem',
	},
	linkStyle: {
		background: 'none',
		border: 'none',
		fontSize: '0.9rem',
		marginTop: '15px',
		cursor: 'pointer',
		textDecoration: 'none',
		transition: '0.35s ease',
		fontWeight: 'bold',
		zIndex: 2,
		textDecorationLine: 'underline',
	},
	cadastroLinkStyle: {
		background: 'none',
		border: 'none',
		fontSize: '0.9rem',
		cursor: 'pointer',
		textDecoration: 'none',
		transition: '0.35s ease',
		zIndex: 2,
		fontWeight: 'normal',
		marginTop: '10px',
		display: 'flex',
		gap: '5px',
		justifyContent: 'center',
		margin: '10px 0 0 0',
		textDecorationLine: 'none',
	},
};
